name: "Deploy to server"

on:
  push:
    branches:
      - main
      
jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        # This step clones your code repository into the runner

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }} # Replace with your server hostname
          username: ${{ secrets.SSH_USERNAME }} # Replace with your server username
          key: ${{ secrets.SSH_PRIVATE_KEY }} # Replace with your SSH private key content
          port: 22
          script: |
            cd /var/www/kp-project  # Change this to your project directory on the server
            git pull origin main  # Updates your code on the server
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh  
            php artisan migrate:fresh  # Runs database migrations (if applicable)
            php artisan optimize:clear
            npm install  # Installs Node.js dependencies
            npm run build  # Runs your build script (assuming you have one)
            composer install  # Installs PHP dependencies
            composer dump-autoload  # Generates optimized autoloader file (optional)
         
